//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAuthenticationWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.IssueingBookDetails = new HashSet<IssueingBookDetail>();
        }
    
        public int BookID { get; set; }
        public string BookTitle { get; set; }
        public string AuthorName { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> NoOfPage { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string ImageFile { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueingBookDetail> IssueingBookDetails { get; set; }
    }
}
