//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAuthenticationWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueingBookDetail
    {
        public int SerialID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public Nullable<System.DateTime> DateofReceived { get; set; }
        public string ActualReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
